### ISSUE TITLE
Fix projects rake tasks overwriting

### ISSUE THREAD

**Issue by jmarsh24** [nerdgeschoss/shimmer#76] opened 2023-08-27 07:40 UTC
Currently there are various projects where the db tasks are overwritten with `rails db:pulll` instead of `rails db:pull`. I think the standard way of addressing this issue is that everything in shimmer should be namespaced under `shimmer` as to prevent this issue.

**Comment by Adeynack** [comment] 2023-10-02 13:50
Duplicate of #32

**Closed by Adeynack** 2023-10-02 13:50 UTC
